### ISSUE TITLE
SwiftZipUtils methods inaccessible in application target.

### ISSUE THREAD

**Issue by lomatrix** [SwiftZip/SwiftZip#12]
For example: save method  from ZipEntry extension is inaccessible

```
let zip = try? ZipArchive(url: fileURL)
_ = try? zip.entries().first?.save(to: unzipedFileURL)
```
![scr](https://user-images.githubusercontent.com/39466996/106505044-6e36ea80-64d0-11eb-9fe2-ea2f91128b5a.png)

**Comment by victor-pavlychko** [comment]
Please make sure you have `import SwiftZipUtils` in your project. The library was split into two parts: core libzip wrapper + set of utilities built on top of the libzip.

**Comment by victor-pavlychko** [comment]
Ooh... there is a problem in the `Package.swift` file, will fix that. Thanks for the heads up!
