### ISSUE TITLE
Expose libzip's built-in encoding guessing

### ISSUE THREAD

**Issue by OCJvanDijk** [SwiftZip/SwiftZip#9]
Hi, 

First of all, great project. I think a solid Swift wrapper around libzip is just what the Swift community needs.

I'm having some problems with 0.0.3. I see you replaced libzip's built-in encoding guessing with a Foundation based one. I'm sure there are good reasons, but for my purposes this is much too slow. It causes a ~600% slowdown of my code in comparison to 0.0.2, to the point where ~85% of the total time searching for and extracting a file is spent on encoding guessing (very large zip file).

I think it would be a good idea to expose the built-in strategy from Swift, preferably by default. Maybe decodingStrategy could be an enum with an additional case for Foundation based guessing.

**Comment by OCJvanDijk** [comment]
Another option: since this is a wrapper for libzip, maybe consider removing the Foundation based guessing from the library altogether. Users could still call ZipEntry.getRawName() and do this from outside the library. Just my two cents.

**Comment by victor-pavlychko** [comment]
Hi,

Thanks for the kind words :slightly_smiling_face:

I'm leaning towards splitting the library into two parts: basic libzip wrapper + utility library. The former can contain Foundation-based encoding guessing, extract to disk, and other helper functions.

**Comment by OCJvanDijk** [comment]
Sounds good to me 👍

For now I'll be happily using 0.0.2 as I only need the main file reading APIs.

**Comment by victor-pavlychko** [comment]
Should be fixed in 0.0.5 (after #11)
